
register(
    id = 'database-differences-report',
    name = _("Database Differences Report"),
    description = _("Compares an external database with the current one."),
    version = '1.0.4',
    gramps_target_version = '3.4',
    include_in_listing = False,
    status = STABLE,
    fname = 'differences.py',
    ptype = REPORT,
    authors = ["Doug Blank"],
    authors_email = ["doug.blank@gmail.com"],
    category = CATEGORY_TEXT,
    reportclass = 'DifferencesReport',
    optionclass = 'DifferencesOptions',
    report_modes = [REPORT_MODE_GUI, REPORT_MODE_BKI, REPORT_MODE_CLI],
    require_active = False,
)
register(GENERAL, 
         id="diff",
         name=_("diff"), 
         description = _("Backported modules from Doug's implementation"),
         status = STABLE,
         version = '0.0.2',
         gramps_target_version = "3.4",
         include_in_listing = False,
         fname ="diff.py",
         load_on_reg = True,
         )
register(GENERAL, 
         id="dictionary", 
         name=_("dictionary"), 
         description = _("Backported modules from Doug's implementation"),
         status = STABLE,
         version = '0.0.3',
         gramps_target_version = "3.4",
         include_in_listing = False,
         fname ="dictionary.py",
         load_on_reg = True,
         )
