register(GRAMPLET, 
         id = "Ancestor", 
         name=_("Ancestor"), 
         description = _("Gramplet showing active person's ancestors"),
         status = STABLE,
         fname="ancestor.py",
         height=100,
         expand=True,
         gramplet = 'Ancestor',
         gramplet_title=_("Ancestors"),
         detached_width = 500,
         detached_height = 500,
         version = '1.0.2',
         gramps_target_version="3.4",
         navtypes=["Person"],
         )
