register(GRAMPLET, 
         id = "Descendant", 
         name=_("Descendant"), 
         description = _("Gramplet showing active person's descendants"),
         status = STABLE,
         fname="descendant.py",
         height=100,
         expand=True,
         gramplet = 'Descendant',
         gramplet_title=_("Descendants"),
         detached_width = 500,
         detached_height = 500,
         version = '1.0.4',
         gramps_target_version="3.4",
         navtypes=["Person"],
         )
